### PR TITLE
Geighz/login feature

### PR DESCRIPTION
**Pull request by geighz**
Merge log in and registration pages to develop branch. Full functionality is not yet there, but front end is completed.

### CODE REVIEW

**Comment by towercodes** [comment]
Is it possible to make the password fields protected so they show *** instead of the actual characters a user is typing? Since I can't test the submit button yet, I don't know if you set the email field to email, so that if a user enters something that is not an email address, it will be rejected.

**Comment by geighz** [comment]
Yes that is possible, but I was aiming for strictly functionality and did not think of adding those details yet. You can see what fields I stored the info in by looking at the console I believe. I am able to handle those common mistakes, would you like for me to work on it now? I'm guessing you'll have to deal with SQL security, as well as possibly also checking if it an email (We can maybe add in a confirmation email later?).  I say while testing, try and get the backend primed for receiving. would you like me to work on the middleware? Or do you want to handle that? I have a bit of it completed, I'm currently using react-form: https://redux-form.com/8.3.0/

**Comment by towercodes** [comment]
Ye, I got the sql stuff down. In summary, my back end:
Does the standard strip slashes from form fields
It checks if the same password has indeed been entered twice.
It uses password_hash to encript the password before it is sent to the database.
All the values are inserted into the database using prepared statements, which minimise the risk of sql injections.

The login simply checks if the password email combo exists. If it does, I've put all the users details in a session except for the password, which I doubt any developer will need.
Is there anything you think I should add to the functionality?



Since the sessions are currently in php, I am still trying to find a way of making those values available to our js developers. So far, I cannot think of anything, but I am confident there is a way.
My second challenge, and the reason I requested a meeting was sending the form to my php script. Ordinarily, the form would have a line that goes <form action = "php script.php" method = "post">, and from there, I would be able to do what I have to do.
The good news is the scripts are done, we just need to connect the backend with your frontend.


PS: Are you still good to meet at 16:30 gmt on Saturday?

**Comment by towercodes** [comment]
`<form action = "php script.php" method = "post">`

**Pull request merged**
